services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  airflow-init:
    build: ./airflow
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init &&
        airflow users create \
          --username karin4os \
          --password admin \
          --firstname Karina \
          --lastname Kuteliya \
          --role Admin \
          --email karina.kuteliya@gmail.com
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "11M18P08k"
      AIRFLOW__WEBSERVER__RBAC: "False"
      AIRFLOW__WEBSERVER__AUTH_BACKENDS: "airflow.www.auth.backend.DefaultAuth"
      AIRFLOW_PIP_INSTALL_REQUIREMENTS: "openpyxl"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
    depends_on:
      - postgres

  airflow-webserver:
    build: ./airflow
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "11M18P08k"
      AIRFLOW__WEBSERVER__RBAC: "False"
      AIRFLOW__WEBSERVER__AUTH_BACKENDS: "airflow.www.auth.backend.DefaultAuth"
      AIRFLOW_PIP_INSTALL_REQUIREMENTS: "openpyxl"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      - airflow-init
      - postgres

  airflow-scheduler:
    build: ./airflow
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "11M18P08k"
      AIRFLOW__WEBSERVER__RBAC: "False"
      AIRFLOW__WEBSERVER__AUTH_BACKENDS: "airflow.www.auth.backend.DefaultAuth"
      AIRFLOW_PIP_INSTALL_REQUIREMENTS: "openpyxl"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
    command: scheduler
    depends_on:
      - airflow-init
      - postgres
  
  streamlit:
    build: ./streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    depends_on:
      - airflow-scheduler

volumes:
  postgres-db-volume:
